### ISSUE TITLE
Text with duplicate words causes error

### ISSUE THREAD

**Issue by rozeappletree** [FelippeChemello/Remotion-TTS-Example#7]
```
proxy-console.js:59 Warning: Encountered two children with the same key, ` the `. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at h1
    at Title (http://localhost:3000/bundle.js:15788:18)
    at div
    at AbsoluteFillRefForwarding (http://localhost:3000/bundle.js:121153:13)
    at div
    at AbsoluteFillRefForwarding (http://localhost:3000/bundle.js:121153:13)
    at HelloWorld (http://localhost:3000/bundle.js:15719:3)
    at Suspense
    at CanUseRemotionHooksProvider (http://localhost:3000/bundle.js:121192:40)
    at div
    at AbsoluteFillRefForwarding (http://localhost:3000/bundle.js:121153:13)
    at ClipComposition (http://localhost:3000/bundle.js:121264:28)
    at Composition (http://localhost:3000/bundle.js:121290:24)
    at RemotionRoot
    at div
    at TimelineZoomContext (http://localhost:3000/bundle.js:46033:32)
    at div
    at HigherZIndex (http://localhost:3000/bundle.js:46130:25)
    at Editor (http://localhost:3000/bundle.js:22934:19)
    at SetTimelineInOutProvider (http://localhost:3000/bundle.js:35272:37)
    at HighestZIndexProvider (http://localhost:3000/bundle.js:45542:34)
    at FolderContextProvider (http://localhost:3000/bundle.js:45507:34)
    at SidebarContextProvider (http://localhost:3000/bundle.js:45974:35)
    at PlayerEmitterProvider (http://localhost:3000/bundle.js:139121:34)
    at MediaVolumeProvider (http://localhost:3000/bundle.js:24265:32)
    at ModalsProvider (http://localhost:3000/bundle.js:25030:27)
    at PreviewSizeProvider (http://localhost:3000/bundle.js:45852:32)
    at ShowGuidesProvider (http://localhost:3000/bundle.js:35302:31)
    at ShowRulersProvider (http://localhost:3000/bundle.js:35356:31)
    at ZoomGesturesProvider (http://localhost:3000/bundle.js:39304:33)
    at CheckerboardProvider (http://localhost:3000/bundle.js:22221:33)
    at KeybindingContextProvider (http://localhost:3000/bundle.js:45662:38)
    at RenderQueueContextProvider (http://localhost:3000/bundle.js:34931:39)
    at PreviewServerConnection (http://localhost:3000/bundle.js:41593:36)
    at ZodProvider (http://localhost:3000/bundle.js:39466:24)
    at EditorContexts (http://localhost:3000/bundle.js:23044:27)
    at BufferingProvider (http://localhost:3000/bundle.js:123516:30)
    at DurationsContextProvider (http://localhost:3000/bundle.js:128307:37)
    at SharedAudioContextProvider (http://localhost:3000/bundle.js:123093:39)
    at ResolveCompositionConfig (http://localhost:3000/bundle.js:122054:37)
    at RenderAssetManagerProvider (http://localhost:3000/bundle.js:121994:39)
    at SequenceManagerProvider (http://localhost:3000/bundle.js:122518:36)
    at CompositionManagerProvider (http://localhost:3000/bundle.js:121410:39)
    at NativeLayersProvider (http://localhost:3000/bundle.js:121830:33)
    at PrefetchProvider (http://localhost:3000/bundle.js:125448:29)
    at EditorPropsProvider (http://localhost:3000/bundle.js:121568:32)
    at RemotionRoot (http://localhost:3000/bundle.js:121911:25)
    at Studio (http://localhost:3000/bundle.js:21141:19) 
```

**Comment by rozeappletree** [comment]
Also, ampersand "&" in text input causes error

**Comment by rozeappletree** [comment]
Here is my text input:
```
Here is the finalized analysis of the S-1 filing:  The analysis of the first part of this S-1 filing yielded the following key takeaways:  Safe and Green Development Corporation, incorporated in Delaware in 2021, engages in real estate development utilizing proprietary technologies from its former parent company, Safe and Green Holdings Corp. The company is registering to resell up to 2,854,843 shares of common stock by selling stockholders Peak One Opportunity Fund and Peak One Investments, which were issued or are issuable pursuant to a debenture private placement and equity line of credit financings.
```
